/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    Button: typeof import('vue-amazing-ui')['Button']
    Divider: typeof import('vue-amazing-ui')['Divider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    InputSearch: typeof import('vue-amazing-ui')['InputSearch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchPage: typeof import('./src/components/SearchPage.vue')['default']
    Space: typeof import('vue-amazing-ui')['Space']
    Table: typeof import('vue-amazing-ui')['Table']
    TableTemplate: typeof import('./src/components/TableTemplate.vue')['default']
    Tag: typeof import('vue-amazing-ui')['Tag']
  }
}
